# -*- coding: utf-8 -*-
"""ProjetV3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dc4PEtXpHrjgtDTODK0aCU1Lbo1cHsqg
"""

#Section 1


import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

# Use the Barbell Strategy, few high growth high risk companies, few stable stocks, and 1 safe sheild
# Company wise spread
TICKERS = [
    # --- HIGH GROWTH (The Engine) ---
    "NVDA",  # AI & Semiconductors (High Volatility)
    "AAPL",  # Consumer Tech (Medium-High Volatility)
    "AMZN",  # Cloud & Retail (High Volatility)

    # --- STABILITY & VALUE (The Ballast) ---
    "JPM",   # Financials (Quality Banking leader)
    "COST",  # Consumer Staples (Consistent Compounder)
    "UNH",   # Healthcare (Defensive Growth)

    # --- THE CRASH SHIELD (The Hedge) ---
    "TLT"    # Long-Term Treasuries (Negative Correlation in crashes)
]
# Pre-2010 data for NVDA/AMZN is less relevant to their current "Tech Giant" status.
START_DATE = "2010-01-01"
# DYNAMIC END DATE: Always gets data up to the exact moment you run the code
END_DATE = datetime.today().strftime('%Y-%m-%d')

#  Fetching the data
def fetch_data(tickers, start, end):
    print(f"--- 1. Downloading Data from {start} to {end} ---")

    # 'Close' column now contains adjusted prices due to auto_adjust=True by default in yfinance
    data = yf.download(tickers, start=start, end=end)['Close']

    # Forward Fill: Handles weekends/holidays/missing data by using previous day's price
    data = data.ffill()

    # Drop any remaining NaNs (e.g., if a stock didn't exist in 2018)
    data = data.dropna()

    print(f"Data Downloaded Successfully. Shape: {data.shape}")
    return data


# 3. PREPROCESSING (Returns & Outliers)

def process_returns(price_data):
    print("\n--- 2. Calculating Returns & Cleaning Outliers ---")

    # Calculate Daily Percentage Change
    returns = price_data.pct_change().dropna()

    # WINSORIZATION (The "Safety Valve")
    # We clip the top 1% and bottom 1% of extreme moves.
    # This prevents a single "flash crash" glitch from breaking the model.
    lower_limit = returns.quantile(0.01)
    upper_limit = returns.quantile(0.99)

    # Apply the clip
    clean_returns = returns.clip(lower=lower_limit, upper=upper_limit, axis=1)

    print("Outliers (1% / 99%) have been clipped.")
    return clean_returns

# MAIN EXECUTION

if __name__ == "__main__":
    # A. Fetch Prices
    prices_df = fetch_data(TICKERS, START_DATE, END_DATE)

    # B. Calculate Clean Returns
    # THIS is the variable ('clean_returns') you will pass to Section 2
    clean_returns = process_returns(prices_df)

    # C. Verification
    print("\n--- 3. Data Check (Last 5 Days) ---")
    print(clean_returns.tail())

    print("\n--- 4. Volatility Check (Risk Ranking) ---")
    # This shows which sectors are risky
    print(clean_returns.std().sort_values(ascending=False))

"""# Section 2"""

# Install pypfopt if not already installed

!pip install PyPortfolioOpt

from pypfopt import HRPOpt
from pypfopt import plotting
import pandas as pd # Make sure pandas is imported here


# Enforcing a minimum 8% weightage contraint
def enforce_min_weights(weights_dict, min_w=0.08):
    """
    Manually forces every asset to have at least 'min_w' weight (e.g., 8%).
    Renormalizes the remaining assets so the total equals 100%.
    """
    weights = pd.Series(weights_dict)

    # 1. Force the floor
    weights[weights < min_w] = min_w

    # 2. Re-normalize the 'Big' weights so the sum is exactly 1.0
    # Calculate how much space is taken by the fixed minimums
    fixed_total = weights[weights == min_w].sum()

    # Identify the flexible assets (those above the minimum)
    flexible_indices = weights[weights > min_w].index

    if len(flexible_indices) > 0:
        # How much room is left for the big assets?
        remaining_budget = 1.0 - fixed_total

        # Scale them down proportionally to fit the budget
        current_flex_total = weights[flexible_indices].sum()
        weights[flexible_indices] *= (remaining_budget / current_flex_total)

    return weights.to_dict()

# 1. THE HRP OPTIMIZATION ENGINE

def run_hrp_model(returns_data):
    print("--- Training HRP Model ---")

    # Initialize. it automatically trains the data and make the covariances
    hrp = HRPOpt(returns=returns_data)

    # Optimize (Raw unconstrained weights)
    raw_weights = hrp.optimize()

    # --- THE CHANGE IS HERE ---
    # Instead of just cleaning, we APPLY THE 8% FLOOR
    print(f"Applying Minimum Weight Constraint: {8}%")
    final_weights = enforce_min_weights(raw_weights, min_w=0.08)

    print("Optimization Complete.")
    print("---------------------------------")
    return hrp, final_weights

# ==========================================
# 2. VISUALIZATION: THE DENDROGRAM (Unchanged)
# ==========================================
def plot_cluster_tree(hrp_instance):
    plt.figure(figsize=(12, 6))
    plt.title("HRP Dendrogram (Blue Chip Clustering)", fontsize=14)
    plt.xlabel("Assets")
    plt.ylabel("Distance (Correlation)")
    plotting.plot_dendrogram(hrp_instance, show_tickers=True)
    plt.show()

# ==========================================
# 3. VISUALIZATION: FINAL ALLOCATION (Updated Title)
# ==========================================
def plot_allocation(weights_dict):
    weights_series = pd.Series(weights_dict).sort_values(ascending=True)

    # Colors: Highlight the Floor (Grey) vs The Growth (Blue)
    # If it's exactly 0.08, it's the floor. If higher, it's a conviction pick.
    colors = ['#4c72b0' if w > 0.081 else '#A9A9A9' for w in weights_series]

    plt.figure(figsize=(10, 6))
    weights_series.plot(kind='barh', color=colors)
    plt.title("Final 'Constrained' Portfolio (Min 8%)", fontsize=14)
    plt.xlabel("Weight")
    plt.grid(axis='x', linestyle='--', alpha=0.5)

    for index, value in enumerate(weights_series):
        plt.text(value, index, f" {value*100:.1f}%", va='center')

    plt.show()

# ==========================================
# MAIN EXECUTION
# ==========================================
if __name__ == "__main__":
    if 'clean_returns' in locals():
        # 1. Run the Model
        hrp_model, optimal_weights = run_hrp_model(clean_returns)

        # 2. Show the "Brain"
        plot_cluster_tree(hrp_model)

        # 3. Show the Results
        plot_allocation(optimal_weights)

        # 4. Text Summary
        print("\n--- FINAL PORTFOLIO WEIGHTS ---")
        for ticker, weight in optimal_weights.items():
            print(f"{ticker}: {weight*100:.2f}%")
    else:
        print("Error: Please run Part 1 first.")

"""# Section 3"""

# ==========================================
# 1. CONFIGURATION
# ==========================================
# Training Window: 504 trading days (approx 2 years) to learn correlations
TRAINING_WINDOW = 504
# Rebalance Frequency: 63 trading days (Quarterly)
REBALANCE_FREQ = 63

def enforce_min_weights(weights_dict, min_w=0.08):
    """
    Forces the 8% floor during backtesting so the simulation
    matches the real strategy.
    """
    weights = pd.Series(weights_dict)

    # Force the floor
    weights[weights < min_w] = min_w

    # Renormalize
    fixed_total = weights[weights == min_w].sum()
    flexible_indices = weights[weights > min_w].index

    if len(flexible_indices) > 0:
        remaining_budget = 1.0 - fixed_total
        current_flex_total = weights[flexible_indices].sum()
        weights[flexible_indices] *= (remaining_budget / current_flex_total)

    return weights.to_dict()

# ==========================================
# 2. THE HRP OPTIMIZER (Helper)
# ==========================================
def get_hrp_weights(historical_data):
    """
    Calculates optimal weights based ONLY on the past data provided.
    """
    try:
        hrp = HRPOpt(returns=historical_data)
        weights = hrp.optimize()
        return enforce_min_weights(weights, min_w=0.08)

    except Exception as e:
        # Fallback to Equal Weights
        n = historical_data.shape[1]
        return {col: 1.0/n for col in historical_data.columns}

# 3. THE WALK-FORWARD BACKTEST LOOP

def run_walk_forward(returns_data):
    print(f"--- Starting Walk-Forward Backtest (Total Days: {len(returns_data)}) ---")

    # We start trading ONLY after the first training window
    start_index = TRAINING_WINDOW
    rebalance_dates = range(start_index, len(returns_data), REBALANCE_FREQ)

    portfolio_history = []

    for i in rebalance_dates:
        # A. Define the PAST (Training Window)
        # Strictly slice [Current - 2 Years] to [Current Day]
        train_window = returns_data.iloc[i-TRAINING_WINDOW : i]

        # B. Define the FUTURE (Test Window)
        # Slice [Current Day] to [Next Rebalance]
        if i + REBALANCE_FREQ >= len(returns_data):
            test_window = returns_data.iloc[i:]
        else:
            test_window = returns_data.iloc[i : i+REBALANCE_FREQ]

        # C. The Decision
        weights = get_hrp_weights(train_window)
        weights_series = pd.Series(weights)

        # D. The Result
        # Multiply future returns by the weights we chose
        period_returns = (test_window * weights_series).sum(axis=1)
        portfolio_history.append(period_returns)

    # Stitch results into one timeline
    full_curve = pd.concat(portfolio_history)
    print("Backtest Complete.")
    return full_curve

# 4. REPORTING: STANDARD TEAR SHEET
# Outputting the results
def generate_standard_report(strategy_rets, benchmark_ticker="SPY"):
    print("\n--- Fetching Benchmark (S&P 500) ---")

    start = strategy_rets.index[0]
    end = strategy_rets.index[-1]

    # robust download
    bench_data = yf.download(benchmark_ticker, start=start, end=end, progress=False)

    # Handle yfinance Data Structure (Fixing the TypeError)
    if isinstance(bench_data, pd.DataFrame):
        # If MultiIndex or extra columns, try to get 'Close' or 'Adj Close'
        if 'Adj Close' in bench_data.columns:
            bench_data = bench_data['Adj Close']
        elif 'Close' in bench_data.columns:
            bench_data = bench_data['Close']

        # If it's still a DataFrame (e.g. SPY as column name), squeeze it
        if isinstance(bench_data, pd.DataFrame):
            bench_data = bench_data.iloc[:, 0]

    bench_rets = bench_data.pct_change().dropna()

    # Align dates
    common_idx = strategy_rets.index.intersection(bench_rets.index)
    strat = strategy_rets.loc[common_idx]
    bench = bench_rets.loc[common_idx]

    # Metrics
    cum_strat = (1 + strat).cumprod()
    cum_bench = (1 + bench).cumprod()

    sharpe_strat = (strat.mean() / strat.std()) * np.sqrt(252)
    sharpe_bench = (bench.mean() / bench.std()) * np.sqrt(252)

    # Max Drawdown Helper
    def get_dd(series):
        roll_max = series.cummax()
        dd = (series - roll_max) / roll_max
        return dd.min()

    mdd_strat = get_dd(cum_strat)
    mdd_bench = get_dd(cum_bench)

    # Helper to extract scalar values safely (The Fix)
    def scalar(x):
        if hasattr(x, "item"): return x.item()
        return x

    print("\n====== STANDARD PERFORMANCE REPORT ======")
    print(f"{'Metric':<20} | {'HRP Strategy':<15} | {'S&P 500 (SPY)':<15}")
    print("-" * 55)
    print(f"{'Total Return':<20} | {(scalar(cum_strat.iloc[-1])-1)*100:.2f}% | {(scalar(cum_bench.iloc[-1])-1)*100:.2f}%")
    print(f"{'Max Drawdown':<20} | {scalar(mdd_strat)*100:.2f}% | {scalar(mdd_bench)*100:.2f}%")
    print(f"{'Sharpe Ratio':<20} | {scalar(sharpe_strat):.2f}   | {scalar(sharpe_bench):.2f}")

    # Plot
    plt.figure(figsize=(12, 6))
    plt.plot(cum_strat, label="HRP (Barbell Portfolio)", color='#2ecc71', linewidth=2)
    plt.plot(cum_bench, label="S&P 500", color='gray', linestyle='--', alpha=0.6)


    plt.title("HRP vs S&P 500: Wealth Preservation Test", fontsize=14)
    plt.ylabel("Growth of $1 Investment")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

    return strat, bench

# ==========================================
# 5. REPORTING: DEFENSIVE METRICS (The "Real" Story)
# ==========================================
def analyze_defensive_metrics(strategy_rets, benchmark_rets):
    print("\n====== DEFENSIVE METRICS (The 'Real' Story) ======")

    # 1. Capture Ratios
    # Upside: How much of the bull market did we catch?
    up_market = benchmark_rets[benchmark_rets > 0]
    strat_up = strategy_rets[benchmark_rets > 0]
    upside_capture = strat_up.mean() / up_market.mean()

    # Downside: How much of the crash did we feel?
    down_market = benchmark_rets[benchmark_rets < 0]
    strat_down = strategy_rets[benchmark_rets < 0]
    downside_capture = strat_down.mean() / down_market.mean()

    # Helper for formatting
    def scalar(x):
        if hasattr(x, "item"): return x.item()
        return x

    print(f"Upside Capture:   {scalar(upside_capture)*100:.2f}% ")
    print(f"Downside Capture: {scalar(downside_capture)*100:.2f}%")

    # 2. Win Rate (Positive Periods)
    positive_months = (strategy_rets > 0).sum() / len(strategy_rets)
    print(f"Win Rate (Days):  {scalar(positive_months)*100:.2f}%")

    print("--------------------------------------------------")
    dc = scalar(downside_capture)
    if dc < 0.6:
        print("✅ SUCCESS: Your model is a 'Crash Shield'.\n   It ignores a huge portion of market losses.")
    else:
        print("⚠️ NOTE: Downside protection is average.")

# ==========================================
# MAIN EXECUTION
# ==========================================
if __name__ == "__main__":
    if 'clean_returns' in locals():
        # 1. Run Walk-Forward
        strategy_curve = run_walk_forward(clean_returns)

        # 2. Standard Report (Returns & Chart)
        strat, bench = generate_standard_report(strategy_curve)

        # 3. Defensive Metrics (Capture Ratios)
        analyze_defensive_metrics(strat, bench)

    else:
        print("Error: Please run Part 1 (Data Collection) first!")

"""# Section 4"""

# ==========================================
# 7. THE HIGHLIGHT REEL (Best Wins)
# ==========================================
def show_top_wins(strategy_rets, benchmark_ticker="SPY"):
    print("Biggest Wins of the model")

    # 1. Get Benchmark Data
    start = strategy_rets.index[0]
    end = strategy_rets.index[-1]
    bench = yf.download(benchmark_ticker, start=start, end=end, progress=False)

    # Clean Benchmark
    if isinstance(bench, pd.DataFrame):
        if 'Adj Close' in bench.columns: bench = bench['Adj Close']
        elif 'Close' in bench.columns: bench = bench['Close']
        if isinstance(bench, pd.DataFrame): bench = bench.iloc[:, 0]

    bench_rets = bench.pct_change().dropna()

    # Align Data
    idx = strategy_rets.index.intersection(bench_rets.index)
    strat = strategy_rets.loc[idx]
    bench = bench_rets.loc[idx]

    # 2. Define Key Events (Manual "Zoom In")
    # We look at specific famous periods to see how we did
    events = [
        ("COVID Crash", "2020-02-19", "2020-03-23"), # The big drop
        ("Post-COVID Rally", "2020-03-23", "2020-08-01"), # The tech boom
        ("2022 Inflation Bear", "2022-01-01", "2022-10-12"), # The slow bleed
        ("AI Boom (Nvidia)", "2023-01-01", "2023-07-31") # The recent rally
    ]

    print(f"{'Event':<20} | {'HRP Return':<12} | {'S&P 500':<12}")
    print("-" * 65)

    for name, s_date, e_date in events:
        try:
            # Slice the specific period
            s_period = strat.loc[s_date:e_date]
            b_period = bench.loc[s_date:e_date]

            if len(s_period) > 0:
                # Calculate Total Return for that specific window
                s_total = (1 + s_period).prod() - 1
                b_total = (1 + b_period).prod() - 1

                # Determine the 'Win'


                print(f"{name:<20} | {s_total*100:6.2f}%      | {b_total*100:6.2f}% ")
        except:
            print(f"{name:<20} |   N/A        |   N/A    ")

    print("-" * 65)

    # 3. Find Best Monthly Outperformance (Automated)
    # Calculate monthly returns
    s_m = strat.resample('M').apply(lambda x: (1 + x).prod() - 1)
    b_m = bench.resample('M').apply(lambda x: (1 + x).prod() - 1)

    diff = s_m - b_m
    best_month = diff.idxmax()
    best_val = diff.max()

    print(f"\n🌟 BEST SINGLE MONTH: {best_month.strftime('%B %Y')}")
    print(f"   We beat the market by +{best_val*100:.2f}% in one month.")

# ==========================================
# MAIN EXECUTION UPDATE
# ==========================================
if __name__ == "__main__":
    if 'clean_returns' in locals():
        # ... (Previous steps: run_walk_forward, generate_report, analyze_defensive) ...
        strategy_curve = run_walk_forward(clean_returns)
        strat, bench = generate_standard_report(strategy_curve)
        analyze_defensive_metrics(strat, bench)

        # --- ADD THIS LINE ---
        show_top_wins(strat)